jsonrpc:
  #  numVerticles: 8
  port: 8080
  apiPath: /
  gracefulShutdownTimeout: 60s
  globalIpRateLimiting:
    enabled: false
    requests: 10
    timeWindow: 1m
    localCacheSize: 5000
  perMethodIpRateLimiting:
    enabled: false
    localCacheSize: 5000
    methods:
      eth_blockNumber:
        requests: 5
        timeWindow: 1m
