jsonrpc:
  #  numVerticles: 8
  port: 8080
  apiPath: /
  gracefulShutdownTimeout: 60s
  callTrackingApiPath: /call-tracking
  accessLogEnabled: true
  globalIpRateLimiting:
    enabled: false # disabled by default, should be enabled via env var if needed
    requests: 60
    timeWindow: 1m
    localCacheSize: 5000
  perMethodIpRateLimiting:
    enabled: false # disabled by default, should be enabled via env var if needed
    localCacheSize: 5000
    methods:
      eth_blockNumber:
        requests: 30
        timeWindow: 1m
